language: csharp
solution: PrimerParcial.sln
dist: trusty
sudo: required
mono: none
dotnet: 3.0.0
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - tylercherield@gmail.com
